### PR TITLE
add mock tables for LAG_NAME_MAP_TABLE in COUNTERS_DB

### PR DESCRIPTION
**Pull request by anilkpandey**
A new COUNTERS_LAG_NAME_MAP table has been added in COUNTERS_DB to keep portchannel OID to name mapping. This change is for adding mock tables related to that.

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Will review after Azure/sonic-swss#885 merged

**Comment by jleveque** [comment]
@qiluo-msft: Please review this PR. Once this is merged, we should be able to un-revert https://github.com/Azure/sonic-py-swsssdk/pull/51.

**Comment by qiluo-msft** [comment]
We need to make decision at this dependency sequence:
1. review and merge https://github.com/Azure/sonic-swss/pull/885
2. advance sonic-swss submodule in sonic-buildimage
2. unrevert https://github.com/Azure/sonic-py-swsssdk/pull/51
3. review and merge this PR.

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Tried cherry-pick to 201911 but not clean. @anilkpandey Could you adapt and submit another PR against 201911 branch?

**Pull request merged**
