### PR TITLE
[rfc2737] fix typo in xcvr removal flow

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by stcheng** [comment]
Retest this please

**Comment by stcheng** [comment]
Retest this please

**Pull request merged**
